### ISSUE TITLE
An error occur on Linux playform

### ISSUE THREAD

**Issue by maple3051** [sheinbergon/jna-aac-encoder#24]
Execuse me, an error occured when I ran the code on Linux. Here is the information, can you help me? Thank you very much~
Ps: In fact, the code is running normally on Windows.
```
java.lang.IllegalArgumentException:` Structure exceeds provided memory bounds
        at com.sun.jna.Structure.ensureAllocated(Structure.java:399)
        at com.sun.jna.Structure.ensureAllocated(Structure.java:379)
        at com.sun.jna.Structure.read(Structure.java:594)
        at com.xxx.videoplayer.audio.jna.structure.AACEncoder.<init>(AACEncoder.java:44)
        at com.xxx.videoplayer.audio.jna.structure.AACEncoder.of(AACEncoder.java:38)
        at com.xxx.videoplayer.audio.jna.FdkAACLibFacade.openEncoder(FdkAACLibFacade.java:76)
```

**Comment by maple3051** [comment]
Sorry, it seems that I used a wrong `so` file. The problem has solved now.
